// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityActivityIntensity string

const (
	ActivityActivityIntensityLow    ActivityActivityIntensity = "Low"
	ActivityActivityIntensityMedium ActivityActivityIntensity = "Medium"
	ActivityActivityIntensityHigh   ActivityActivityIntensity = "High"
)

func (e *ActivityActivityIntensity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityActivityIntensity(s)
	case string:
		*e = ActivityActivityIntensity(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityActivityIntensity: %T", src)
	}
	return nil
}

type NullActivityActivityIntensity struct {
	ActivityActivityIntensity ActivityActivityIntensity `json:"activity_activity_intensity"`
	Valid                     bool                      `json:"valid"` // Valid is true if ActivityActivityIntensity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityActivityIntensity) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityActivityIntensity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityActivityIntensity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityActivityIntensity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityActivityIntensity), nil
}

type SellerAdminStatus string

const (
	SellerAdminStatusActive      SellerAdminStatus = "active"
	SellerAdminStatusSuspended   SellerAdminStatus = "suspended"
	SellerAdminStatusBlacklisted SellerAdminStatus = "blacklisted"
)

func (e *SellerAdminStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SellerAdminStatus(s)
	case string:
		*e = SellerAdminStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SellerAdminStatus: %T", src)
	}
	return nil
}

type NullSellerAdminStatus struct {
	SellerAdminStatus SellerAdminStatus `json:"seller_admin_status"`
	Valid             bool              `json:"valid"` // Valid is true if SellerAdminStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSellerAdminStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SellerAdminStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SellerAdminStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSellerAdminStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SellerAdminStatus), nil
}

type SellerVerificationStatus string

const (
	SellerVerificationStatusPending   SellerVerificationStatus = "pending"
	SellerVerificationStatusApproved  SellerVerificationStatus = "approved"
	SellerVerificationStatusRejected  SellerVerificationStatus = "rejected"
	SellerVerificationStatusSuspended SellerVerificationStatus = "suspended"
)

func (e *SellerVerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SellerVerificationStatus(s)
	case string:
		*e = SellerVerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SellerVerificationStatus: %T", src)
	}
	return nil
}

type NullSellerVerificationStatus struct {
	SellerVerificationStatus SellerVerificationStatus `json:"seller_verification_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if SellerVerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSellerVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SellerVerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SellerVerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSellerVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SellerVerificationStatus), nil
}

type UserCartCartStatus string

const (
	UserCartCartStatusActive    UserCartCartStatus = "active"
	UserCartCartStatusPurchased UserCartCartStatus = "purchased"
	UserCartCartStatusDeleted   UserCartCartStatus = "deleted"
	UserCartCartStatusValue3    UserCartCartStatus = ""
)

func (e *UserCartCartStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserCartCartStatus(s)
	case string:
		*e = UserCartCartStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserCartCartStatus: %T", src)
	}
	return nil
}

type NullUserCartCartStatus struct {
	UserCartCartStatus UserCartCartStatus `json:"user_cart_cart_status"`
	Valid              bool               `json:"valid"` // Valid is true if UserCartCartStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserCartCartStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserCartCartStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserCartCartStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserCartCartStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserCartCartStatus), nil
}

type UserOrderPaymentStatus string

const (
	UserOrderPaymentStatusPending UserOrderPaymentStatus = "Pending"
	UserOrderPaymentStatusPaid    UserOrderPaymentStatus = "Paid"
	UserOrderPaymentStatusFailed  UserOrderPaymentStatus = "Failed"
)

func (e *UserOrderPaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserOrderPaymentStatus(s)
	case string:
		*e = UserOrderPaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserOrderPaymentStatus: %T", src)
	}
	return nil
}

type NullUserOrderPaymentStatus struct {
	UserOrderPaymentStatus UserOrderPaymentStatus `json:"user_order_payment_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if UserOrderPaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserOrderPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserOrderPaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserOrderPaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserOrderPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserOrderPaymentStatus), nil
}

type UserStatus string

const (
	UserStatusActive      UserStatus = "active"
	UserStatusSuspended   UserStatus = "suspended"
	UserStatusBanned      UserStatus = "banned"
	UserStatusDeactivated UserStatus = "deactivated"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type UserTransactionPaymentStatus string

const (
	UserTransactionPaymentStatusPending UserTransactionPaymentStatus = "Pending"
	UserTransactionPaymentStatusSuccess UserTransactionPaymentStatus = "Success"
	UserTransactionPaymentStatusFailed  UserTransactionPaymentStatus = "Failed"
	UserTransactionPaymentStatusExpired UserTransactionPaymentStatus = "Expired"
)

func (e *UserTransactionPaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserTransactionPaymentStatus(s)
	case string:
		*e = UserTransactionPaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserTransactionPaymentStatus: %T", src)
	}
	return nil
}

type NullUserTransactionPaymentStatus struct {
	UserTransactionPaymentStatus UserTransactionPaymentStatus `json:"user_transaction_payment_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if UserTransactionPaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserTransactionPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserTransactionPaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserTransactionPaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserTransactionPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserTransactionPaymentStatus), nil
}

type UserVipVipStatus string

const (
	UserVipVipStatusPending UserVipVipStatus = "Pending"
	UserVipVipStatusActive  UserVipVipStatus = "Active"
	UserVipVipStatusExpired UserVipVipStatus = "Expired"
)

func (e *UserVipVipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserVipVipStatus(s)
	case string:
		*e = UserVipVipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserVipVipStatus: %T", src)
	}
	return nil
}

type NullUserVipVipStatus struct {
	UserVipVipStatus UserVipVipStatus `json:"user_vip_vip_status"`
	Valid            bool             `json:"valid"` // Valid is true if UserVipVipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserVipVipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserVipVipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserVipVipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserVipVipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserVipVipStatus), nil
}

type UsersUserGender string

const (
	UsersUserGenderMale   UsersUserGender = "Male"
	UsersUserGenderFemale UsersUserGender = "Female"
)

func (e *UsersUserGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersUserGender(s)
	case string:
		*e = UsersUserGender(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersUserGender: %T", src)
	}
	return nil
}

type NullUsersUserGender struct {
	UsersUserGender UsersUserGender `json:"users_user_gender"`
	Valid           bool            `json:"valid"` // Valid is true if UsersUserGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersUserGender) Scan(value interface{}) error {
	if value == nil {
		ns.UsersUserGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersUserGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersUserGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersUserGender), nil
}

type Activity struct {
	ID                  int32          `json:"id"`
	ActivityCode        pgtype.Text    `json:"activity_code"`
	ActivityName        string         `json:"activity_name"`
	Description         pgtype.Text    `json:"description"`
	ImageUrl            pgtype.Text    `json:"image_url"`
	MetValue            pgtype.Numeric `json:"met_value"`
	MeasurementUnit     pgtype.Text    `json:"measurement_unit"`
	RecommendedMinValue pgtype.Numeric `json:"recommended_min_value"`
}

type ActivityType struct {
	ActivityTypeID int32       `json:"activity_type_id"`
	ActivityCode   string      `json:"activity_code"`
	DisplayName    string      `json:"display_name"`
	IntensityLevel pgtype.Text `json:"intensity_level"`
}

type Admin struct {
	AdminID      pgtype.UUID        `json:"admin_id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

type AdminRefreshToken struct {
	ID           pgtype.UUID        `json:"id"`
	AdminID      pgtype.UUID        `json:"admin_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    pgtype.Bool        `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Food struct {
	FoodID                  pgtype.UUID        `json:"food_id"`
	SellerID                pgtype.UUID        `json:"seller_id"`
	FoodName                string             `json:"food_name"`
	Description             pgtype.Text        `json:"description"`
	Price                   pgtype.Numeric     `json:"price"`
	Currency                string             `json:"currency"`
	PhotoUrl                pgtype.Text        `json:"photo_url"`
	ThumbnailUrl            pgtype.Text        `json:"thumbnail_url"`
	IsAvailable             pgtype.Bool        `json:"is_available"`
	StockCount              pgtype.Int4        `json:"stock_count"`
	Tags                    []string           `json:"tags"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ServingSize             pgtype.Text        `json:"serving_size"`
	ServingSizeGrams        pgtype.Numeric     `json:"serving_size_grams"`
	Quantity                pgtype.Numeric     `json:"quantity"`
	Calories                pgtype.Int4        `json:"calories"`
	CarbsGrams              pgtype.Numeric     `json:"carbs_grams"`
	FiberGrams              pgtype.Numeric     `json:"fiber_grams"`
	ProteinGrams            pgtype.Numeric     `json:"protein_grams"`
	FatGrams                pgtype.Numeric     `json:"fat_grams"`
	SugarGrams              pgtype.Numeric     `json:"sugar_grams"`
	SodiumMg                pgtype.Numeric     `json:"sodium_mg"`
	GlycemicIndex           pgtype.Int4        `json:"glycemic_index"`
	GlycemicLoad            pgtype.Numeric     `json:"glycemic_load"`
	FoodCategory            []string           `json:"food_category"`
	SaturatedFatGrams       pgtype.Numeric     `json:"saturated_fat_grams"`
	MonounsaturatedFatGrams pgtype.Numeric     `json:"monounsaturated_fat_grams"`
	PolyunsaturatedFatGrams pgtype.Numeric     `json:"polyunsaturated_fat_grams"`
	CholesterolMg           pgtype.Numeric     `json:"cholesterol_mg"`
	IsActive                pgtype.Bool        `json:"is_active"`
	IsApproved              pgtype.Text        `json:"is_approved"`
	RejectionReason         pgtype.Text        `json:"rejection_reason"`
}

type FoodCategory struct {
	CategoryID   int32       `json:"category_id"`
	CategoryCode string      `json:"category_code"`
	DisplayName  string      `json:"display_name"`
	Description  pgtype.Text `json:"description"`
}

type HealthConditionType struct {
	ConditionID   int32       `json:"condition_id"`
	ConditionCode string      `json:"condition_code"`
	DisplayName   string      `json:"display_name"`
	Description   pgtype.Text `json:"description"`
}

type LogsAuth struct {
	LogID       pgtype.UUID        `json:"log_id"`
	UserID      pgtype.Text        `json:"user_id"`
	LogCategory string             `json:"log_category"`
	LogAction   string             `json:"log_action"`
	LogMessage  string             `json:"log_message"`
	LogLevel    pgtype.Text        `json:"log_level"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MealType struct {
	MealTypeID  int32  `json:"meal_type_id"`
	DisplayName string `json:"display_name"`
}

type OtpCode struct {
	OtpID               pgtype.UUID        `json:"otp_id"`
	EntityID            pgtype.UUID        `json:"entity_id"`
	EntityRole          string             `json:"entity_role"`
	OtpSecret           string             `json:"otp_secret"`
	OtpPurpose          string             `json:"otp_purpose"`
	OtpAttempts         int32              `json:"otp_attempts"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	DeletionScheduledAt pgtype.Timestamptz `json:"deletion_scheduled_at"`
}

type PendingRegistration struct {
	PendingID      pgtype.UUID        `json:"pending_id"`
	EntityRole     string             `json:"entity_role"`
	Email          string             `json:"email"`
	Username       pgtype.Text        `json:"username"`
	HashedPassword string             `json:"hashed_password"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	RawData        []byte             `json:"raw_data"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RecommendationEffectiveness struct {
	UserID                string      `json:"user_id"`
	UserConditionID       pgtype.Int4 `json:"user_condition_id"`
	MealType              pgtype.Text `json:"meal_type"`
	RecommendationDate    pgtype.Date `json:"recommendation_date"`
	FoodsRecommended      int64       `json:"foods_recommended"`
	FoodsViewed           int64       `json:"foods_viewed"`
	FoodsPurchased        int64       `json:"foods_purchased"`
	AvgFoodRating         float64     `json:"avg_food_rating"`
	ActivitiesRecommended int64       `json:"activities_recommended"`
	ActivitiesViewed      int64       `json:"activities_viewed"`
	ActivitiesCompleted   int64       `json:"activities_completed"`
	AvgActivityRating     float64     `json:"avg_activity_rating"`
	OverallFeedback       pgtype.Text `json:"overall_feedback"`
}

type RecommendationSession struct {
	SessionID           pgtype.UUID        `json:"session_id"`
	UserID              string             `json:"user_id"`
	RequestedTypes      []string           `json:"requested_types"`
	MealType            pgtype.Text        `json:"meal_type"`
	FoodCategoryCodes   []string           `json:"food_category_codes"`
	FoodPreferences     pgtype.Text        `json:"food_preferences"`
	ActivityTypeCodes   []string           `json:"activity_type_codes"`
	ActivityPreferences pgtype.Text        `json:"activity_preferences"`
	InsightsQuestion    pgtype.Text        `json:"insights_question"`
	AnalysisSummary     string             `json:"analysis_summary"`
	InsightsResponse    pgtype.Text        `json:"insights_response"`
	LatestGlucoseValue  pgtype.Int4        `json:"latest_glucose_value"`
	LatestHba1c         pgtype.Numeric     `json:"latest_hba1c"`
	UserConditionID     pgtype.Int4        `json:"user_condition_id"`
	AiModelUsed         pgtype.Text        `json:"ai_model_used"`
	AiConfidenceScore   pgtype.Numeric     `json:"ai_confidence_score"`
	OverallFeedback     pgtype.Text        `json:"overall_feedback"`
	FeedbackNotes       pgtype.Text        `json:"feedback_notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

type RecommendedActivity struct {
	RecommendationActivityID   pgtype.UUID        `json:"recommendation_activity_id"`
	SessionID                  pgtype.UUID        `json:"session_id"`
	ActivityID                 int32              `json:"activity_id"`
	Reason                     string             `json:"reason"`
	RecommendedDurationMinutes int32              `json:"recommended_duration_minutes"`
	RecommendedIntensity       pgtype.Text        `json:"recommended_intensity"`
	SafetyNotes                pgtype.Text        `json:"safety_notes"`
	BestTimeOfDay              pgtype.Text        `json:"best_time_of_day"`
	RecommendationRank         pgtype.Int4        `json:"recommendation_rank"`
	WasViewed                  pgtype.Bool        `json:"was_viewed"`
	WasCompleted               pgtype.Bool        `json:"was_completed"`
	ActualDurationMinutes      pgtype.Int4        `json:"actual_duration_minutes"`
	UserRating                 pgtype.Int4        `json:"user_rating"`
	FeedbackNotes              pgtype.Text        `json:"feedback_notes"`
	GlucoseChangeAfterActivity pgtype.Int4        `json:"glucose_change_after_activity"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	CompletedAt                pgtype.Timestamptz `json:"completed_at"`
	LastInteractionAt          pgtype.Timestamptz `json:"last_interaction_at"`
}

type RecommendedFood struct {
	RecommendationFoodID    pgtype.UUID        `json:"recommendation_food_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	FoodID                  pgtype.UUID        `json:"food_id"`
	Reason                  string             `json:"reason"`
	NutritionHighlight      pgtype.Text        `json:"nutrition_highlight"`
	SuggestedMealType       pgtype.Text        `json:"suggested_meal_type"`
	SuggestedPortionSize    pgtype.Text        `json:"suggested_portion_size"`
	RecommendationRank      pgtype.Int4        `json:"recommendation_rank"`
	WasViewed               pgtype.Bool        `json:"was_viewed"`
	WasAddedToCart          pgtype.Bool        `json:"was_added_to_cart"`
	WasPurchased            pgtype.Bool        `json:"was_purchased"`
	WasLoggedAsMeal         pgtype.Bool        `json:"was_logged_as_meal"`
	UserRating              pgtype.Int4        `json:"user_rating"`
	FeedbackNotes           pgtype.Text        `json:"feedback_notes"`
	GlucoseSpikeAfterEating pgtype.Int4        `json:"glucose_spike_after_eating"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	LastInteractionAt       pgtype.Timestamptz `json:"last_interaction_at"`
}

type Role struct {
	RoleID   int32  `json:"role_id"`
	RoleName string `json:"role_name"`
}

type SellerProfile struct {
	SellerID           pgtype.UUID           `json:"seller_id"`
	UserID             string                `json:"user_id"`
	CreatedAt          pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz    `json:"updated_at"`
	StoreName          string                `json:"store_name"`
	StoreDescription   pgtype.Text           `json:"store_description"`
	StorePhoneNumber   pgtype.Text           `json:"store_phone_number"`
	IsOpen             bool                  `json:"is_open"`
	BusinessHours      []byte                `json:"business_hours"`
	VerificationStatus string                `json:"verification_status"`
	LogoUrl            pgtype.Text           `json:"logo_url"`
	BannerUrl          pgtype.Text           `json:"banner_url"`
	AddressLine1       pgtype.Text           `json:"address_line1"`
	AddressLine2       pgtype.Text           `json:"address_line2"`
	District           pgtype.Text           `json:"district"`
	City               pgtype.Text           `json:"city"`
	Province           pgtype.Text           `json:"province"`
	PostalCode         pgtype.Text           `json:"postal_code"`
	Latitude           pgtype.Numeric        `json:"latitude"`
	Longitude          pgtype.Numeric        `json:"longitude"`
	GmapsLink          pgtype.Text           `json:"gmaps_link"`
	StoreSlug          string                `json:"store_slug"`
	StoreEmail         pgtype.Text           `json:"store_email"`
	WebsiteUrl         pgtype.Text           `json:"website_url"`
	SocialMediaLinks   []byte                `json:"social_media_links"`
	IsActive           pgtype.Bool           `json:"is_active"`
	CuisineType        []string              `json:"cuisine_type"`
	PriceRange         pgtype.Int4           `json:"price_range"`
	RejectionReason    pgtype.Text           `json:"rejection_reason"`
	VerifiedAt         pgtype.Timestamptz    `json:"verified_at"`
	AverageRating      pgtype.Numeric        `json:"average_rating"`
	ReviewCount        pgtype.Int4           `json:"review_count"`
	AdminStatus        NullSellerAdminStatus `json:"admin_status"`
	SuspensionReason   pgtype.Text           `json:"suspension_reason"`
	AdminNotes         pgtype.Text           `json:"admin_notes"`
}

type SellerReview struct {
	ReviewID    pgtype.UUID        `json:"review_id"`
	OrderID     pgtype.UUID        `json:"order_id"`
	UserID      string             `json:"user_id"`
	SellerID    pgtype.UUID        `json:"seller_id"`
	Rating      int32              `json:"rating"`
	ReviewText  pgtype.Text        `json:"review_text"`
	SellerReply pgtype.Text        `json:"seller_reply"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SystemSetting struct {
	Key       string             `json:"key"`
	Value     bool               `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Unified user table supporting both traditional username/password and OAuth authentication
type User struct {
	UserID string `json:"user_id"`
	// Username for traditional auth (NULL for OAuth-only users)
	UserUsername pgtype.Text `json:"user_username"`
	// Hashed password for traditional auth (NULL for OAuth-only users)
	UserPassword  pgtype.Text `json:"user_password"`
	UserFirstname pgtype.Text `json:"user_firstname"`
	UserLastname  pgtype.Text `json:"user_lastname"`
	// Primary email (used for both auth types)
	UserEmail       pgtype.Text         `json:"user_email"`
	UserDob         pgtype.Date         `json:"user_dob"`
	UserGender      NullUsersUserGender `json:"user_gender"`
	UserAccounttype pgtype.Int2         `json:"user_accounttype"`
	UserNameAuth    pgtype.Text         `json:"user_name_auth"`
	UserAvatarUrl   pgtype.Text         `json:"user_avatar_url"`
	// OAuth provider name (google, facebook, etc.) - NULL for traditional auth
	UserProvider pgtype.Text `json:"user_provider"`
	// User ID from OAuth provider - NULL for traditional auth
	UserProviderUserID pgtype.Text        `json:"user_provider_user_id"`
	UserRawData        []byte             `json:"user_raw_data"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	UserLastLoginAt    pgtype.Timestamptz `json:"user_last_login_at"`
	// Email from OAuth provider (may differ from primary email)
	UserEmailAuth pgtype.Text `json:"user_email_auth"`
	// Whether user has verified their email via OTP
	IsEmailVerified pgtype.Bool        `json:"is_email_verified"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	Status          NullUserStatus     `json:"status"`
	StatusReason    pgtype.Text        `json:"status_reason"`
	StatusUpdatedAt pgtype.Timestamptz `json:"status_updated_at"`
	AdminNotes      pgtype.Text        `json:"admin_notes"`
}

type UserActivityLog struct {
	ActivityID        pgtype.UUID        `json:"activity_id"`
	UserID            string             `json:"user_id"`
	ActivityTimestamp pgtype.Timestamptz `json:"activity_timestamp"`
	ActivityCode      string             `json:"activity_code"`
	Intensity         string             `json:"intensity"`
	PerceivedExertion pgtype.Int4        `json:"perceived_exertion"`
	DurationMinutes   int32              `json:"duration_minutes"`
	StepsCount        pgtype.Int4        `json:"steps_count"`
	PreActivityCarbs  pgtype.Int4        `json:"pre_activity_carbs"`
	WaterIntakeMl     pgtype.Int4        `json:"water_intake_ml"`
	IssueDescription  pgtype.Text        `json:"issue_description"`
	Source            string             `json:"source"`
	SyncID            pgtype.Text        `json:"sync_id"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserAddress struct {
	AddressID         pgtype.UUID        `json:"address_id"`
	UserID            string             `json:"user_id"`
	AddressLine1      string             `json:"address_line1"`
	AddressLine2      pgtype.Text        `json:"address_line2"`
	AddressCity       string             `json:"address_city"`
	AddressProvince   pgtype.Text        `json:"address_province"`
	AddressPostalcode pgtype.Text        `json:"address_postalcode"`
	AddressLatitude   pgtype.Float8      `json:"address_latitude"`
	AddressLongitude  pgtype.Float8      `json:"address_longitude"`
	AddressLabel      string             `json:"address_label"`
	RecipientName     pgtype.Text        `json:"recipient_name"`
	RecipientPhone    pgtype.Text        `json:"recipient_phone"`
	DeliveryNotes     pgtype.Text        `json:"delivery_notes"`
	IsDefault         bool               `json:"is_default"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	AddressDistrict   pgtype.Text        `json:"address_district"`
}

type UserCart struct {
	CartID    pgtype.UUID        `json:"cart_id"`
	UserID    string             `json:"user_id"`
	SellerID  pgtype.UUID        `json:"seller_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserCartItem struct {
	CartItemID pgtype.UUID `json:"cart_item_id"`
	CartID     pgtype.UUID `json:"cart_id"`
	FoodID     pgtype.UUID `json:"food_id"`
	Quantity   int32       `json:"quantity"`
}

type UserEmailChangeRequest struct {
	RequestID         pgtype.UUID        `json:"request_id"`
	UserID            string             `json:"user_id"`
	NewEmail          string             `json:"new_email"`
	VerificationToken string             `json:"verification_token"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type UserGlucoseReading struct {
	ReadingID        pgtype.UUID        `json:"reading_id"`
	UserID           string             `json:"user_id"`
	GlucoseValue     int32              `json:"glucose_value"`
	ReadingTimestamp pgtype.Timestamptz `json:"reading_timestamp"`
	ReadingType      string             `json:"reading_type"`
	TrendArrow       pgtype.Text        `json:"trend_arrow"`
	RateOfChange     pgtype.Int4        `json:"rate_of_change"`
	Source           pgtype.Text        `json:"source"`
	DeviceID         pgtype.Text        `json:"device_id"`
	DeviceName       pgtype.Text        `json:"device_name"`
	IsFlagged        pgtype.Bool        `json:"is_flagged"`
	FlagReason       pgtype.Text        `json:"flag_reason"`
	IsOutlier        pgtype.Bool        `json:"is_outlier"`
	Notes            pgtype.Text        `json:"notes"`
	Symptoms         []string           `json:"symptoms"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UserHba1cRecord struct {
	Hba1cID             pgtype.UUID        `json:"hba1c_id"`
	UserID              string             `json:"user_id"`
	TestDate            pgtype.Date        `json:"test_date"`
	Hba1cPercentage     pgtype.Numeric     `json:"hba1c_percentage"`
	Hba1cMmolMol        pgtype.Int4        `json:"hba1c_mmol_mol"`
	EstimatedAvgGlucose pgtype.Int4        `json:"estimated_avg_glucose"`
	TreatmentChanged    pgtype.Bool        `json:"treatment_changed"`
	MedicationChanges   pgtype.Text        `json:"medication_changes"`
	DietChanges         pgtype.Text        `json:"diet_changes"`
	ActivityChanges     pgtype.Text        `json:"activity_changes"`
	ChangeFromPrevious  pgtype.Numeric     `json:"change_from_previous"`
	Trend               pgtype.Text        `json:"trend"`
	Notes               pgtype.Text        `json:"notes"`
	DocumentUrl         pgtype.Text        `json:"document_url"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type UserHealthEvent struct {
	EventID                  pgtype.UUID        `json:"event_id"`
	UserID                   string             `json:"user_id"`
	EventDate                pgtype.Date        `json:"event_date"`
	EventType                string             `json:"event_type"`
	Severity                 pgtype.Text        `json:"severity"`
	GlucoseValue             pgtype.Int4        `json:"glucose_value"`
	KetoneValueMmol          pgtype.Numeric     `json:"ketone_value_mmol"`
	Symptoms                 []string           `json:"symptoms"`
	Treatments               []string           `json:"treatments"`
	RequiredMedicalAttention pgtype.Bool        `json:"required_medical_attention"`
	Notes                    pgtype.Text        `json:"notes"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Text        `json:"updated_at"`
}

type UserHealthProfile struct {
	ProfileID                  pgtype.UUID        `json:"profile_id"`
	UserID                     string             `json:"user_id"`
	AppExperience              string             `json:"app_experience"`
	ConditionID                int32              `json:"condition_id"`
	DiagnosisDate              pgtype.Date        `json:"diagnosis_date"`
	YearsWithCondition         pgtype.Numeric     `json:"years_with_condition"`
	TreatmentTypes             []string           `json:"treatment_types"`
	TargetGlucoseFasting       pgtype.Int4        `json:"target_glucose_fasting"`
	TargetGlucosePostprandial  pgtype.Int4        `json:"target_glucose_postprandial"`
	UsesCgm                    pgtype.Bool        `json:"uses_cgm"`
	CgmDevice                  pgtype.Text        `json:"cgm_device"`
	CgmApiConnected            pgtype.Bool        `json:"cgm_api_connected"`
	HeightCm                   pgtype.Numeric     `json:"height_cm"`
	CurrentWeightKg            pgtype.Numeric     `json:"current_weight_kg"`
	TargetWeightKg             pgtype.Numeric     `json:"target_weight_kg"`
	Bmi                        pgtype.Numeric     `json:"bmi"`
	WaistCircumferenceCm       pgtype.Numeric     `json:"waist_circumference_cm"`
	BodyFatPercentage          pgtype.Numeric     `json:"body_fat_percentage"`
	Hba1cTarget                pgtype.Numeric     `json:"hba1c_target"`
	LastHba1c                  pgtype.Numeric     `json:"last_hba1c"`
	LastHba1cDate              pgtype.Date        `json:"last_hba1c_date"`
	ActivityLevel              pgtype.Text        `json:"activity_level"`
	DailyStepsGoal             pgtype.Int4        `json:"daily_steps_goal"`
	WeeklyExerciseGoalMinutes  pgtype.Int4        `json:"weekly_exercise_goal_minutes"`
	PreferredActivityTypeIds   []int32            `json:"preferred_activity_type_ids"`
	DietaryPattern             pgtype.Text        `json:"dietary_pattern"`
	DailyCarbTargetGrams       pgtype.Int4        `json:"daily_carb_target_grams"`
	DailyCalorieTarget         pgtype.Int4        `json:"daily_calorie_target"`
	DailyProteinTargetGrams    pgtype.Int4        `json:"daily_protein_target_grams"`
	DailyFatTargetGrams        pgtype.Int4        `json:"daily_fat_target_grams"`
	MealsPerDay                pgtype.Int4        `json:"meals_per_day"`
	SnacksPerDay               pgtype.Int4        `json:"snacks_per_day"`
	FoodAllergies              []string           `json:"food_allergies"`
	FoodIntolerances           []string           `json:"food_intolerances"`
	FoodsToAvoid               []string           `json:"foods_to_avoid"`
	CulturalCuisines           []string           `json:"cultural_cuisines"`
	DietaryRestrictions        []string           `json:"dietary_restrictions"`
	HasHypertension            pgtype.Bool        `json:"has_hypertension"`
	HypertensionMedication     pgtype.Text        `json:"hypertension_medication"`
	HasKidneyDisease           pgtype.Bool        `json:"has_kidney_disease"`
	KidneyDiseaseStage         pgtype.Int4        `json:"kidney_disease_stage"`
	EgfrValue                  pgtype.Numeric     `json:"egfr_value"`
	HasCardiovascularDisease   pgtype.Bool        `json:"has_cardiovascular_disease"`
	HasNeuropathy              pgtype.Bool        `json:"has_neuropathy"`
	HasRetinopathy             pgtype.Bool        `json:"has_retinopathy"`
	HasGastroparesis           pgtype.Bool        `json:"has_gastroparesis"`
	HasHypoglycemiaUnawareness pgtype.Bool        `json:"has_hypoglycemia_unawareness"`
	OtherConditions            []string           `json:"other_conditions"`
	SmokingStatus              pgtype.Text        `json:"smoking_status"`
	SmokingYears               pgtype.Int4        `json:"smoking_years"`
	AlcoholFrequency           pgtype.Text        `json:"alcohol_frequency"`
	AlcoholDrinksPerWeek       pgtype.Int4        `json:"alcohol_drinks_per_week"`
	StressLevel                pgtype.Text        `json:"stress_level"`
	TypicalSleepHours          pgtype.Numeric     `json:"typical_sleep_hours"`
	SleepQuality               pgtype.Text        `json:"sleep_quality"`
	IsPregnant                 pgtype.Bool        `json:"is_pregnant"`
	IsBreastfeeding            pgtype.Bool        `json:"is_breastfeeding"`
	ExpectedDueDate            pgtype.Date        `json:"expected_due_date"`
	PreferredUnits             pgtype.Text        `json:"preferred_units"`
	GlucoseUnit                pgtype.Text        `json:"glucose_unit"`
	Timezone                   pgtype.Text        `json:"timezone"`
	LanguageCode               pgtype.Text        `json:"language_code"`
	EnableGlucoseAlerts        pgtype.Bool        `json:"enable_glucose_alerts"`
	EnableMealReminders        pgtype.Bool        `json:"enable_meal_reminders"`
	EnableActivityReminders    pgtype.Bool        `json:"enable_activity_reminders"`
	EnableMedicationReminders  pgtype.Bool        `json:"enable_medication_reminders"`
	ShareDataForResearch       pgtype.Bool        `json:"share_data_for_research"`
	ShareAnonymizedData        pgtype.Bool        `json:"share_anonymized_data"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type UserMealItem struct {
	ItemID                  pgtype.UUID        `json:"item_id"`
	MealID                  pgtype.UUID        `json:"meal_id"`
	FoodName                string             `json:"food_name"`
	FoodID                  pgtype.UUID        `json:"food_id"`
	Seller                  pgtype.Text        `json:"seller"`
	ServingSize             pgtype.Text        `json:"serving_size"`
	ServingSizeGrams        pgtype.Numeric     `json:"serving_size_grams"`
	Quantity                pgtype.Numeric     `json:"quantity"`
	Calories                pgtype.Int4        `json:"calories"`
	CarbsGrams              pgtype.Numeric     `json:"carbs_grams"`
	FiberGrams              pgtype.Numeric     `json:"fiber_grams"`
	ProteinGrams            pgtype.Numeric     `json:"protein_grams"`
	FatGrams                pgtype.Numeric     `json:"fat_grams"`
	SugarGrams              pgtype.Numeric     `json:"sugar_grams"`
	SodiumMg                pgtype.Int4        `json:"sodium_mg"`
	GlycemicIndex           pgtype.Int4        `json:"glycemic_index"`
	GlycemicLoad            pgtype.Numeric     `json:"glycemic_load"`
	FoodCategory            pgtype.Text        `json:"food_category"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SaturatedFatGrams       pgtype.Numeric     `json:"saturated_fat_grams"`
	MonounsaturatedFatGrams pgtype.Numeric     `json:"monounsaturated_fat_grams"`
	PolyunsaturatedFatGrams pgtype.Numeric     `json:"polyunsaturated_fat_grams"`
	CholesterolMg           pgtype.Int4        `json:"cholesterol_mg"`
}

type UserMealLog struct {
	MealID            pgtype.UUID        `json:"meal_id"`
	UserID            string             `json:"user_id"`
	MealTimestamp     pgtype.Timestamptz `json:"meal_timestamp"`
	MealTypeID        int32              `json:"meal_type_id"`
	Description       pgtype.Text        `json:"description"`
	TotalCalories     pgtype.Int4        `json:"total_calories"`
	TotalCarbsGrams   pgtype.Numeric     `json:"total_carbs_grams"`
	TotalProteinGrams pgtype.Numeric     `json:"total_protein_grams"`
	TotalFatGrams     pgtype.Numeric     `json:"total_fat_grams"`
	TotalFiberGrams   pgtype.Numeric     `json:"total_fiber_grams"`
	TotalSugarGrams   pgtype.Numeric     `json:"total_sugar_grams"`
	Tags              []string           `json:"tags"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserMedication struct {
	MedicationID    int32              `json:"medication_id"`
	UserID          pgtype.Text        `json:"user_id"`
	DisplayName     string             `json:"display_name"`
	MedicationType  string             `json:"medication_type"`
	DefaultDoseUnit pgtype.Text        `json:"default_dose_unit"`
	IsActive        pgtype.Bool        `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserMedicationLog struct {
	MedicationlogID         pgtype.UUID        `json:"medicationlog_id"`
	UserID                  string             `json:"user_id"`
	MedicationID            pgtype.Int4        `json:"medication_id"`
	MedicationName          string             `json:"medication_name"`
	Timestamp               pgtype.Timestamptz `json:"timestamp"`
	DoseAmount              pgtype.Numeric     `json:"dose_amount"`
	Reason                  pgtype.Text        `json:"reason"`
	IsPumpDelivery          pgtype.Bool        `json:"is_pump_delivery"`
	DeliveryDurationMinutes pgtype.Int4        `json:"delivery_duration_minutes"`
	Notes                   pgtype.Text        `json:"notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type UserOrder struct {
	OrderID             pgtype.UUID        `json:"order_id"`
	UserID              string             `json:"user_id"`
	SellerID            pgtype.UUID        `json:"seller_id"`
	TotalPrice          pgtype.Numeric     `json:"total_price"`
	Status              string             `json:"status"`
	DeliveryAddressJson []byte             `json:"delivery_address_json"`
	PaymentStatus       string             `json:"payment_status"`
	PaymentMethod       pgtype.Text        `json:"payment_method"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	SellerNotes         pgtype.Text        `json:"seller_notes"`
}

type UserOrderItem struct {
	OrderItemID      pgtype.UUID    `json:"order_item_id"`
	OrderID          pgtype.UUID    `json:"order_id"`
	FoodID           pgtype.UUID    `json:"food_id"`
	Quantity         int32          `json:"quantity"`
	PriceAtPurchase  pgtype.Numeric `json:"price_at_purchase"`
	FoodNameSnapshot string         `json:"food_name_snapshot"`
}

type UserRole struct {
	UserID string `json:"user_id"`
	RoleID int32  `json:"role_id"`
}

type UserSleepLog struct {
	SleepID           pgtype.UUID        `json:"sleep_id"`
	UserID            string             `json:"user_id"`
	SleepDate         pgtype.Date        `json:"sleep_date"`
	BedTime           pgtype.Timestamptz `json:"bed_time"`
	WakeTime          pgtype.Timestamptz `json:"wake_time"`
	QualityRating     pgtype.Int4        `json:"quality_rating"`
	TrackerScore      pgtype.Int4        `json:"tracker_score"`
	DeepSleepMinutes  pgtype.Int4        `json:"deep_sleep_minutes"`
	RemSleepMinutes   pgtype.Int4        `json:"rem_sleep_minutes"`
	LightSleepMinutes pgtype.Int4        `json:"light_sleep_minutes"`
	AwakeMinutes      pgtype.Int4        `json:"awake_minutes"`
	AverageHrv        pgtype.Int4        `json:"average_hrv"`
	RestingHeartRate  pgtype.Int4        `json:"resting_heart_rate"`
	Tags              []string           `json:"tags"`
	Source            pgtype.Text        `json:"source"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UsersRefreshToken struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            string             `json:"user_id"`
	TokenHash         string             `json:"token_hash"`
	DeviceInfo        pgtype.Text        `json:"device_info"`
	IpAddress         *netip.Addr        `json:"ip_address"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenID pgtype.UUID        `json:"replaced_by_token_id"`
}
