// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE user_email = $1
) AS exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, userEmail pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, userEmail)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE user_username = $1
) AS exists
`

func (q *Queries) CheckUsernameExists(ctx context.Context, userUsername pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, userUsername)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countUserAddresses = `-- name: CountUserAddresses :one
SELECT COUNT(*) FROM user_addresses
WHERE user_id = $1
`

func (q *Queries) CountUserAddresses(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserAddresses, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO users_refresh_tokens (
    user_id,
    token_hash,
    device_info,
    ip_address,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, token_hash, device_info, ip_address, expires_at, created_at, revoked_at, replaced_by_token_id
`

type CreateRefreshTokenParams struct {
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Refresh Tokens (renamed table)
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UsersRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i UsersRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id,
    user_username,
    user_password,
    user_firstname,
    user_lastname,
    user_email,
    user_dob,
    user_gender,
    user_accounttype
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth
`

type CreateUserParams struct {
	UserID          string              `json:"user_id"`
	UserUsername    pgtype.Text         `json:"user_username"`
	UserPassword    pgtype.Text         `json:"user_password"`
	UserFirstname   pgtype.Text         `json:"user_firstname"`
	UserLastname    pgtype.Text         `json:"user_lastname"`
	UserEmail       pgtype.Text         `json:"user_email"`
	UserDob         pgtype.Date         `json:"user_dob"`
	UserGender      NullUsersUserGender `json:"user_gender"`
	UserAccounttype pgtype.Int2         `json:"user_accounttype"`
}

// Traditional Auth Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.UserUsername,
		arg.UserPassword,
		arg.UserFirstname,
		arg.UserLastname,
		arg.UserEmail,
		arg.UserDob,
		arg.UserGender,
		arg.UserAccounttype,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
	)
	return i, err
}

const createUserAddress = `-- name: CreateUserAddress :one
INSERT INTO user_addresses (
    user_id,
    address_line1,
    address_line2,
    address_city,
    address_province,
    address_postalcode,
    address_latitude,
    address_longitude,
    address_label,
    is_default
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, is_default
`

type CreateUserAddressParams struct {
	UserID            string         `json:"user_id"`
	AddressLine1      string         `json:"address_line1"`
	AddressLine2      pgtype.Text    `json:"address_line2"`
	AddressCity       string         `json:"address_city"`
	AddressProvince   pgtype.Text    `json:"address_province"`
	AddressPostalcode pgtype.Text    `json:"address_postalcode"`
	AddressLatitude   pgtype.Numeric `json:"address_latitude"`
	AddressLongitude  pgtype.Numeric `json:"address_longitude"`
	AddressLabel      pgtype.Text    `json:"address_label"`
	IsDefault         pgtype.Bool    `json:"is_default"`
}

// User Addresses
func (q *Queries) CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, createUserAddress,
		arg.UserID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressProvince,
		arg.AddressPostalcode,
		arg.AddressLatitude,
		arg.AddressLongitude,
		arg.AddressLabel,
		arg.IsDefault,
	)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.IsDefault,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM users_refresh_tokens
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const deleteUserAddress = `-- name: DeleteUserAddress :exec
DELETE FROM user_addresses
WHERE address_id = $1 AND user_id = $2
`

type DeleteUserAddressParams struct {
	AddressID int64  `json:"address_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) error {
	_, err := q.db.Exec(ctx, deleteUserAddress, arg.AddressID, arg.UserID)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, is_default FROM user_addresses
WHERE address_id = $1 AND user_id = $2
`

type GetAddressByIDParams struct {
	AddressID int64  `json:"address_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetAddressByID(ctx context.Context, arg GetAddressByIDParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getAddressByID, arg.AddressID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.IsDefault,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, device_info, ip_address, expires_at, created_at, revoked_at, replaced_by_token_id FROM users_refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (UsersRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i UsersRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const getUserActiveRefreshTokens = `-- name: GetUserActiveRefreshTokens :many
SELECT id, user_id, token_hash, device_info, ip_address, expires_at, created_at, revoked_at, replaced_by_token_id FROM users_refresh_tokens
WHERE user_id = $1 
  AND revoked_at IS NULL 
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

func (q *Queries) GetUserActiveRefreshTokens(ctx context.Context, userID string) ([]UsersRefreshToken, error) {
	rows, err := q.db.Query(ctx, getUserActiveRefreshTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersRefreshToken
	for rows.Next() {
		var i UsersRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.ReplacedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, is_default FROM user_addresses
WHERE user_id = $1
ORDER BY is_default DESC, address_id DESC
`

func (q *Queries) GetUserAddresses(ctx context.Context, userID string) ([]UserAddress, error) {
	rows, err := q.db.Query(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAddress
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.AddressID,
			&i.UserID,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.AddressCity,
			&i.AddressProvince,
			&i.AddressPostalcode,
			&i.AddressLatitude,
			&i.AddressLongitude,
			&i.AddressLabel,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth FROM users
WHERE user_email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, userEmail pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, userEmail)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
	)
	return i, err
}

const getUserByOAuthEmail = `-- name: GetUserByOAuthEmail :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth FROM users
WHERE user_email_auth = $1 AND user_provider IS NOT NULL
`

func (q *Queries) GetUserByOAuthEmail(ctx context.Context, userEmailAuth pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuthEmail, userEmailAuth)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth FROM users
WHERE user_provider = $1 AND user_provider_user_id = $2
`

type GetUserByProviderIDParams struct {
	UserProvider       pgtype.Text `json:"user_provider"`
	UserProviderUserID pgtype.Text `json:"user_provider_user_id"`
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderID, arg.UserProvider, arg.UserProviderUserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth FROM users
WHERE user_username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, userUsername pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, userUsername)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
	)
	return i, err
}

const getUserDefaultAddress = `-- name: GetUserDefaultAddress :one
SELECT address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, is_default FROM user_addresses
WHERE user_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetUserDefaultAddress(ctx context.Context, userID string) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getUserDefaultAddress, userID)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.IsDefault,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE users_refresh_tokens 
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE users_refresh_tokens 
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const setDefaultAddress = `-- name: SetDefaultAddress :exec
UPDATE user_addresses
SET is_default = (address_id = $2)
WHERE user_id = $1
`

type SetDefaultAddressParams struct {
	UserID    string `json:"user_id"`
	AddressID int64  `json:"address_id"`
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) error {
	_, err := q.db.Exec(ctx, setDefaultAddress, arg.UserID, arg.AddressID)
	return err
}

const updateRefreshTokenReplacement = `-- name: UpdateRefreshTokenReplacement :exec
UPDATE users_refresh_tokens
SET replaced_by_token_id = $2
WHERE id = $1
`

type UpdateRefreshTokenReplacementParams struct {
	ID                pgtype.UUID `json:"id"`
	ReplacedByTokenID pgtype.UUID `json:"replaced_by_token_id"`
}

func (q *Queries) UpdateRefreshTokenReplacement(ctx context.Context, arg UpdateRefreshTokenReplacementParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenReplacement, arg.ID, arg.ReplacedByTokenID)
	return err
}

const updateUserAddress = `-- name: UpdateUserAddress :one
UPDATE user_addresses
SET
    address_line1 = COALESCE($3, address_line1),
    address_line2 = COALESCE($4, address_line2),
    address_city = COALESCE($5, address_city),
    address_province = COALESCE($6, address_province),
    address_postalcode = COALESCE($7, address_postalcode),
    address_latitude = COALESCE($8, address_latitude),
    address_longitude = COALESCE($9, address_longitude),
    address_label = COALESCE($10, address_label)
WHERE address_id = $1 AND user_id = $2
RETURNING address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, is_default
`

type UpdateUserAddressParams struct {
	AddressID         int64          `json:"address_id"`
	UserID            string         `json:"user_id"`
	AddressLine1      string         `json:"address_line1"`
	AddressLine2      pgtype.Text    `json:"address_line2"`
	AddressCity       string         `json:"address_city"`
	AddressProvince   pgtype.Text    `json:"address_province"`
	AddressPostalcode pgtype.Text    `json:"address_postalcode"`
	AddressLatitude   pgtype.Numeric `json:"address_latitude"`
	AddressLongitude  pgtype.Numeric `json:"address_longitude"`
	AddressLabel      pgtype.Text    `json:"address_label"`
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, updateUserAddress,
		arg.AddressID,
		arg.UserID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressProvince,
		arg.AddressPostalcode,
		arg.AddressLatitude,
		arg.AddressLongitude,
		arg.AddressLabel,
	)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.IsDefault,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET user_last_login_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, userID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET 
    user_firstname = COALESCE($2, user_firstname),
    user_lastname = COALESCE($3, user_lastname),
    user_email = COALESCE($4, user_email),
    user_dob = COALESCE($5, user_dob),
    user_gender = COALESCE($6, user_gender)
WHERE user_id = $1
RETURNING user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth
`

type UpdateUserProfileParams struct {
	UserID        string              `json:"user_id"`
	UserFirstname pgtype.Text         `json:"user_firstname"`
	UserLastname  pgtype.Text         `json:"user_lastname"`
	UserEmail     pgtype.Text         `json:"user_email"`
	UserDob       pgtype.Date         `json:"user_dob"`
	UserGender    NullUsersUserGender `json:"user_gender"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.UserFirstname,
		arg.UserLastname,
		arg.UserEmail,
		arg.UserDob,
		arg.UserGender,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
	)
	return i, err
}

const upsertOAuthUser = `-- name: UpsertOAuthUser :one
INSERT INTO users (
    user_id,
    user_email,
    user_name_auth,
    user_avatar_url,
    user_provider,
    user_provider_user_id,
    user_raw_data,
    user_last_login_at,
    user_email_auth,
    user_username,
    user_password
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (user_provider, user_provider_user_id) 
DO UPDATE SET 
    -- Update fields based on EXCLUDED (the row that was attempted to be inserted)
    user_email = COALESCE(EXCLUDED.user_email, users.user_email),
    user_name_auth = EXCLUDED.user_name_auth,
    user_avatar_url = EXCLUDED.user_avatar_url,
    user_raw_data = EXCLUDED.user_raw_data,
    user_last_login_at = EXCLUDED.user_last_login_at, -- Menggunakan nilai login time dari EXCLUDED ($8)
    user_updated_at_auth = CURRENT_TIMESTAMP -- Menggunakan CURRENT_TIMESTAMP untuk mencatat pembaruan skema auth
RETURNING user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth
`

type UpsertOAuthUserParams struct {
	UserID             string             `json:"user_id"`
	UserEmail          pgtype.Text        `json:"user_email"`
	UserNameAuth       pgtype.Text        `json:"user_name_auth"`
	UserAvatarUrl      pgtype.Text        `json:"user_avatar_url"`
	UserProvider       pgtype.Text        `json:"user_provider"`
	UserProviderUserID pgtype.Text        `json:"user_provider_user_id"`
	UserRawData        []byte             `json:"user_raw_data"`
	UserLastLoginAt    pgtype.Timestamptz `json:"user_last_login_at"`
	UserEmailAuth      pgtype.Text        `json:"user_email_auth"`
	UserUsername       pgtype.Text        `json:"user_username"`
	UserPassword       pgtype.Text        `json:"user_password"`
}

// OAuth Integration - Upsert user with OAuth data
func (q *Queries) UpsertOAuthUser(ctx context.Context, arg UpsertOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertOAuthUser,
		arg.UserID,
		arg.UserEmail,
		arg.UserNameAuth,
		arg.UserAvatarUrl,
		arg.UserProvider,
		arg.UserProviderUserID,
		arg.UserRawData,
		arg.UserLastLoginAt,
		arg.UserEmailAuth,
		arg.UserUsername,
		arg.UserPassword,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
	)
	return i, err
}
