// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAddressOwnership = `-- name: CheckAddressOwnership :one
SELECT EXISTS(
    SELECT 1 FROM user_addresses
    WHERE address_id = $1 AND user_id = $2 AND is_active = true
)
`

type CheckAddressOwnershipParams struct {
	AddressID pgtype.UUID `json:"address_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) CheckAddressOwnership(ctx context.Context, arg CheckAddressOwnershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAddressOwnership, arg.AddressID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE user_email = $1
) AS exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, userEmail pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, userEmail)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM users WHERE user_username = $1
) AS exists
`

func (q *Queries) CheckUsernameExists(ctx context.Context, userUsername pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, userUsername)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const cleanupExpiredRefreshTokens = `-- name: CleanupExpiredRefreshTokens :exec
DELETE FROM users_refresh_tokens
WHERE expires_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) CleanupExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredRefreshTokens)
	return err
}

const cleanupRevokedRefreshTokens = `-- name: CleanupRevokedRefreshTokens :exec
DELETE FROM users_refresh_tokens
WHERE revoked_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) CleanupRevokedRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupRevokedRefreshTokens)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM user_cart_items
WHERE cart_id = $1
`

// Deletes all items from a cart
func (q *Queries) ClearCart(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const clearCartSeller = `-- name: ClearCartSeller :exec
UPDATE user_carts
SET seller_id = NULL, updated_at = NOW()
WHERE cart_id = $1
`

// This is called when the last item is removed from a cart
func (q *Queries) ClearCartSeller(ctx context.Context, cartID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearCartSeller, cartID)
	return err
}

const countActiveOTPCodes = `-- name: CountActiveOTPCodes :one
SELECT COUNT(*) FROM otp_codes
WHERE expires_at > NOW()
`

// Count OTPs that haven't expired yet
func (q *Queries) CountActiveOTPCodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOTPCodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserAddresses = `-- name: CountUserAddresses :one
SELECT COUNT(*) FROM user_addresses
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) CountUserAddresses(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserAddresses, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthLog = `-- name: CreateAuthLog :one
INSERT INTO logs_auth (
    user_id,
    log_category,
    log_action,
    log_message,
    log_level,
    ip_address,
    user_agent,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING log_id, user_id, log_category, log_action, log_message, log_level, ip_address, user_agent, metadata, created_at
`

type CreateAuthLogParams struct {
	UserID      pgtype.Text `json:"user_id"`
	LogCategory string      `json:"log_category"`
	LogAction   string      `json:"log_action"`
	LogMessage  string      `json:"log_message"`
	LogLevel    pgtype.Text `json:"log_level"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateAuthLog(ctx context.Context, arg CreateAuthLogParams) (LogsAuth, error) {
	row := q.db.QueryRow(ctx, createAuthLog,
		arg.UserID,
		arg.LogCategory,
		arg.LogAction,
		arg.LogMessage,
		arg.LogLevel,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i LogsAuth
	err := row.Scan(
		&i.LogID,
		&i.UserID,
		&i.LogCategory,
		&i.LogAction,
		&i.LogMessage,
		&i.LogLevel,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createCart = `-- name: CreateCart :one
INSERT INTO user_carts (user_id)
VALUES ($1)
RETURNING cart_id, user_id, seller_id, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, userID string) (UserCart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i UserCart
	err := row.Scan(
		&i.CartID,
		&i.UserID,
		&i.SellerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmailChangeRequest = `-- name: CreateEmailChangeRequest :one
INSERT INTO user_email_change_requests (
    user_id,
    new_email,
    verification_token,
    expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING request_id, user_id, new_email, verification_token, expires_at, created_at
`

type CreateEmailChangeRequestParams struct {
	UserID            string             `json:"user_id"`
	NewEmail          string             `json:"new_email"`
	VerificationToken string             `json:"verification_token"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailChangeRequest(ctx context.Context, arg CreateEmailChangeRequestParams) (UserEmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, createEmailChangeRequest,
		arg.UserID,
		arg.NewEmail,
		arg.VerificationToken,
		arg.ExpiresAt,
	)
	var i UserEmailChangeRequest
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.NewEmail,
		&i.VerificationToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOTPCode = `-- name: CreateOTPCode :one
INSERT INTO otp_codes (
    entity_id,
    entity_role,
    otp_secret,
    otp_purpose,
    otp_attempts,
    expires_at,
    deletion_scheduled_at
) VALUES (
    $1, $2, $3, $4, 0, $5, $6
)
RETURNING otp_id, entity_id, entity_role, otp_secret, otp_purpose, otp_attempts, expires_at, created_at, deletion_scheduled_at
`

type CreateOTPCodeParams struct {
	EntityID            pgtype.UUID        `json:"entity_id"`
	EntityRole          string             `json:"entity_role"`
	OtpSecret           string             `json:"otp_secret"`
	OtpPurpose          string             `json:"otp_purpose"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	DeletionScheduledAt pgtype.Timestamptz `json:"deletion_scheduled_at"`
}

func (q *Queries) CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTPCode,
		arg.EntityID,
		arg.EntityRole,
		arg.OtpSecret,
		arg.OtpPurpose,
		arg.ExpiresAt,
		arg.DeletionScheduledAt,
	)
	var i OtpCode
	err := row.Scan(
		&i.OtpID,
		&i.EntityID,
		&i.EntityRole,
		&i.OtpSecret,
		&i.OtpPurpose,
		&i.OtpAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO user_orders (
    user_id,
    seller_id,
    total_price,
    status,
    delivery_address_json,
    payment_status,
    payment_method
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING order_id, user_id, seller_id, total_price, status, delivery_address_json, payment_status, payment_method, created_at
`

type CreateOrderParams struct {
	UserID              string         `json:"user_id"`
	SellerID            pgtype.UUID    `json:"seller_id"`
	TotalPrice          pgtype.Numeric `json:"total_price"`
	Status              string         `json:"status"`
	DeliveryAddressJson []byte         `json:"delivery_address_json"`
	PaymentStatus       string         `json:"payment_status"`
	PaymentMethod       pgtype.Text    `json:"payment_method"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (UserOrder, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.SellerID,
		arg.TotalPrice,
		arg.Status,
		arg.DeliveryAddressJson,
		arg.PaymentStatus,
		arg.PaymentMethod,
	)
	var i UserOrder
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.SellerID,
		&i.TotalPrice,
		&i.Status,
		&i.DeliveryAddressJson,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO user_order_items (
    order_id,
    food_id,
    quantity,
    price_at_purchase,
    food_name_snapshot
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING order_item_id, order_id, food_id, quantity, price_at_purchase, food_name_snapshot
`

type CreateOrderItemParams struct {
	OrderID          pgtype.UUID    `json:"order_id"`
	FoodID           pgtype.UUID    `json:"food_id"`
	Quantity         int32          `json:"quantity"`
	PriceAtPurchase  pgtype.Numeric `json:"price_at_purchase"`
	FoodNameSnapshot string         `json:"food_name_snapshot"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (UserOrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.FoodID,
		arg.Quantity,
		arg.PriceAtPurchase,
		arg.FoodNameSnapshot,
	)
	var i UserOrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderID,
		&i.FoodID,
		&i.Quantity,
		&i.PriceAtPurchase,
		&i.FoodNameSnapshot,
	)
	return i, err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :one
INSERT INTO pending_registrations
    (entity_role, email, username, hashed_password, first_name, last_name, raw_data, expires_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING pending_id
`

type CreatePendingRegistrationParams struct {
	EntityRole     string             `json:"entity_role"`
	Email          string             `json:"email"`
	Username       pgtype.Text        `json:"username"`
	HashedPassword string             `json:"hashed_password"`
	FirstName      pgtype.Text        `json:"first_name"`
	LastName       pgtype.Text        `json:"last_name"`
	RawData        []byte             `json:"raw_data"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPendingRegistration,
		arg.EntityRole,
		arg.Email,
		arg.Username,
		arg.HashedPassword,
		arg.FirstName,
		arg.LastName,
		arg.RawData,
		arg.ExpiresAt,
	)
	var pending_id pgtype.UUID
	err := row.Scan(&pending_id)
	return pending_id, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO users_refresh_tokens (
    user_id,
    token_hash,
    device_info,
    ip_address,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, token_hash, device_info, ip_address, expires_at, created_at, revoked_at, replaced_by_token_id
`

type CreateRefreshTokenParams struct {
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo pgtype.Text        `json:"device_info"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Refresh Tokens (renamed table)
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (UsersRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i UsersRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id,
    user_username,
    user_password,
    user_firstname,
    user_lastname,
    user_email,
    user_dob,
    user_gender,
    user_accounttype,
    user_created_at_auth,
    is_email_verified,
    email_verified_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth, is_email_verified, email_verified_at
`

type CreateUserParams struct {
	UserID            string              `json:"user_id"`
	UserUsername      pgtype.Text         `json:"user_username"`
	UserPassword      pgtype.Text         `json:"user_password"`
	UserFirstname     pgtype.Text         `json:"user_firstname"`
	UserLastname      pgtype.Text         `json:"user_lastname"`
	UserEmail         pgtype.Text         `json:"user_email"`
	UserDob           pgtype.Date         `json:"user_dob"`
	UserGender        NullUsersUserGender `json:"user_gender"`
	UserAccounttype   pgtype.Int2         `json:"user_accounttype"`
	UserCreatedAtAuth pgtype.Timestamptz  `json:"user_created_at_auth"`
	IsEmailVerified   pgtype.Bool         `json:"is_email_verified"`
	EmailVerifiedAt   pgtype.Timestamptz  `json:"email_verified_at"`
}

// Traditional Auth Users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.UserUsername,
		arg.UserPassword,
		arg.UserFirstname,
		arg.UserLastname,
		arg.UserEmail,
		arg.UserDob,
		arg.UserGender,
		arg.UserAccounttype,
		arg.UserCreatedAtAuth,
		arg.IsEmailVerified,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
		&i.IsEmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const createUserAddress = `-- name: CreateUserAddress :one
INSERT INTO user_addresses (
    user_id,
    address_line1,
    address_line2,
    address_city,
    address_province,
    address_postalcode,
    address_latitude,
    address_longitude,
    address_label,
    recipient_name,
    recipient_phone,
    delivery_notes,
    is_default
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, recipient_name, recipient_phone, delivery_notes, is_default, is_active, created_at, updated_at
`

type CreateUserAddressParams struct {
	UserID            string        `json:"user_id"`
	AddressLine1      string        `json:"address_line1"`
	AddressLine2      pgtype.Text   `json:"address_line2"`
	AddressCity       string        `json:"address_city"`
	AddressProvince   pgtype.Text   `json:"address_province"`
	AddressPostalcode pgtype.Text   `json:"address_postalcode"`
	AddressLatitude   pgtype.Float8 `json:"address_latitude"`
	AddressLongitude  pgtype.Float8 `json:"address_longitude"`
	AddressLabel      string        `json:"address_label"`
	RecipientName     pgtype.Text   `json:"recipient_name"`
	RecipientPhone    pgtype.Text   `json:"recipient_phone"`
	DeliveryNotes     pgtype.Text   `json:"delivery_notes"`
	IsDefault         bool          `json:"is_default"`
}

func (q *Queries) CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, createUserAddress,
		arg.UserID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressProvince,
		arg.AddressPostalcode,
		arg.AddressLatitude,
		arg.AddressLongitude,
		arg.AddressLabel,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.DeliveryNotes,
		arg.IsDefault,
	)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.DeliveryNotes,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM user_cart_items
WHERE cart_id = $1 AND food_id = $2
`

type DeleteCartItemParams struct {
	CartID pgtype.UUID `json:"cart_id"`
	FoodID pgtype.UUID `json:"food_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.CartID, arg.FoodID)
	return err
}

const deleteEmailChangeRequest = `-- name: DeleteEmailChangeRequest :exec
DELETE FROM user_email_change_requests
WHERE
    request_id = $1
`

func (q *Queries) DeleteEmailChangeRequest(ctx context.Context, requestID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailChangeRequest, requestID)
	return err
}

const deleteExpiredPendingRegistrations = `-- name: DeleteExpiredPendingRegistrations :exec
DELETE FROM pending_registrations
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredPendingRegistrations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPendingRegistrations)
	return err
}

const deleteOTPCode = `-- name: DeleteOTPCode :exec
DELETE FROM otp_codes
WHERE otp_id = $1
`

func (q *Queries) DeleteOTPCode(ctx context.Context, otpID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOTPCode, otpID)
	return err
}

const deleteOTPCodeByEntityID = `-- name: DeleteOTPCodeByEntityID :exec
DELETE FROM otp_codes
WHERE entity_id = $1
`

func (q *Queries) DeleteOTPCodeByEntityID(ctx context.Context, entityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOTPCodeByEntityID, entityID)
	return err
}

const deleteOldAuthLogs = `-- name: DeleteOldAuthLogs :exec
DELETE FROM logs_auth
WHERE created_at < $1
`

func (q *Queries) DeleteOldAuthLogs(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldAuthLogs, createdAt)
	return err
}

const deletePendingRegistration = `-- name: DeletePendingRegistration :exec
DELETE FROM pending_registrations
WHERE pending_id = $1
`

func (q *Queries) DeletePendingRegistration(ctx context.Context, pendingID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingRegistration, pendingID)
	return err
}

const deleteScheduledOTPCodes = `-- name: DeleteScheduledOTPCodes :exec
DELETE FROM otp_codes
WHERE deletion_scheduled_at IS NOT NULL 
AND deletion_scheduled_at <= NOW()
`

// Delete OTPs that are scheduled for deletion and time has passed
func (q *Queries) DeleteScheduledOTPCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteScheduledOTPCodes)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const deleteUserAddress = `-- name: DeleteUserAddress :exec
UPDATE user_addresses
SET is_active = false, is_default = false
WHERE address_id = $1 AND user_id = $2
`

type DeleteUserAddressParams struct {
	AddressID pgtype.UUID `json:"address_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) DeleteUserAddress(ctx context.Context, arg DeleteUserAddressParams) error {
	_, err := q.db.Exec(ctx, deleteUserAddress, arg.AddressID, arg.UserID)
	return err
}

const getAuthLogsByCategory = `-- name: GetAuthLogsByCategory :many
SELECT log_id, user_id, log_category, log_action, log_message, log_level, ip_address, user_agent, metadata, created_at FROM logs_auth
WHERE log_category = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuthLogsByCategoryParams struct {
	LogCategory string `json:"log_category"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) GetAuthLogsByCategory(ctx context.Context, arg GetAuthLogsByCategoryParams) ([]LogsAuth, error) {
	rows, err := q.db.Query(ctx, getAuthLogsByCategory, arg.LogCategory, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogsAuth
	for rows.Next() {
		var i LogsAuth
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.LogCategory,
			&i.LogAction,
			&i.LogMessage,
			&i.LogLevel,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthLogsByDateRange = `-- name: GetAuthLogsByDateRange :many
SELECT log_id, user_id, log_category, log_action, log_message, log_level, ip_address, user_agent, metadata, created_at FROM logs_auth
WHERE created_at BETWEEN $1 AND $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetAuthLogsByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) GetAuthLogsByDateRange(ctx context.Context, arg GetAuthLogsByDateRangeParams) ([]LogsAuth, error) {
	rows, err := q.db.Query(ctx, getAuthLogsByDateRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogsAuth
	for rows.Next() {
		var i LogsAuth
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.LogCategory,
			&i.LogAction,
			&i.LogMessage,
			&i.LogLevel,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthLogsByUserID = `-- name: GetAuthLogsByUserID :many
SELECT log_id, user_id, log_category, log_action, log_message, log_level, ip_address, user_agent, metadata, created_at FROM logs_auth
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAuthLogsByUserIDParams struct {
	UserID pgtype.Text `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetAuthLogsByUserID(ctx context.Context, arg GetAuthLogsByUserIDParams) ([]LogsAuth, error) {
	rows, err := q.db.Query(ctx, getAuthLogsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogsAuth
	for rows.Next() {
		var i LogsAuth
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.LogCategory,
			&i.LogAction,
			&i.LogMessage,
			&i.LogLevel,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT cart_id, user_id, seller_id, created_at, updated_at FROM user_carts
WHERE user_id = $1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID string) (UserCart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i UserCart
	err := row.Scan(
		&i.CartID,
		&i.UserID,
		&i.SellerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT 
    ci.cart_item_id, ci.cart_id, ci.food_id, ci.quantity,
    f.food_name,
    f.price,
    f.photo_url,
    f.seller_id
FROM user_cart_items ci
JOIN foods f ON ci.food_id = f.food_id
WHERE ci.cart_id = $1
`

type GetCartItemsRow struct {
	CartItemID pgtype.UUID    `json:"cart_item_id"`
	CartID     pgtype.UUID    `json:"cart_id"`
	FoodID     pgtype.UUID    `json:"food_id"`
	Quantity   int32          `json:"quantity"`
	FoodName   string         `json:"food_name"`
	Price      pgtype.Numeric `json:"price"`
	PhotoUrl   pgtype.Text    `json:"photo_url"`
	SellerID   pgtype.UUID    `json:"seller_id"`
}

func (q *Queries) GetCartItems(ctx context.Context, cartID pgtype.UUID) ([]GetCartItemsRow, error) {
	rows, err := q.db.Query(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsRow
	for rows.Next() {
		var i GetCartItemsRow
		if err := rows.Scan(
			&i.CartItemID,
			&i.CartID,
			&i.FoodID,
			&i.Quantity,
			&i.FoodName,
			&i.Price,
			&i.PhotoUrl,
			&i.SellerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDefaultAddress = `-- name: GetDefaultAddress :one
SELECT address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, recipient_name, recipient_phone, delivery_notes, is_default, is_active, created_at, updated_at FROM user_addresses
WHERE user_id = $1 AND is_default = true AND is_active = true
LIMIT 1
`

func (q *Queries) GetDefaultAddress(ctx context.Context, userID string) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getDefaultAddress, userID)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.DeliveryNotes,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailChangeRequestByToken = `-- name: GetEmailChangeRequestByToken :one
SELECT request_id, user_id, new_email, verification_token, expires_at, created_at
FROM user_email_change_requests
WHERE
    verification_token = $1
`

func (q *Queries) GetEmailChangeRequestByToken(ctx context.Context, verificationToken string) (UserEmailChangeRequest, error) {
	row := q.db.QueryRow(ctx, getEmailChangeRequestByToken, verificationToken)
	var i UserEmailChangeRequest
	err := row.Scan(
		&i.RequestID,
		&i.UserID,
		&i.NewEmail,
		&i.VerificationToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFailedLoginAttempts = `-- name: GetFailedLoginAttempts :many
SELECT log_id, user_id, log_category, log_action, log_message, log_level, ip_address, user_agent, metadata, created_at FROM logs_auth
WHERE log_category = 'login'
  AND log_action = 'login_failed'
  AND created_at > $1
ORDER BY created_at DESC
`

func (q *Queries) GetFailedLoginAttempts(ctx context.Context, createdAt pgtype.Timestamptz) ([]LogsAuth, error) {
	rows, err := q.db.Query(ctx, getFailedLoginAttempts, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogsAuth
	for rows.Next() {
		var i LogsAuth
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.LogCategory,
			&i.LogAction,
			&i.LogMessage,
			&i.LogLevel,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodForUpdate = `-- name: GetFoodForUpdate :one
SELECT food_id, food_name, price, stock_count, is_available FROM foods
WHERE food_id = $1
FOR UPDATE
`

type GetFoodForUpdateRow struct {
	FoodID      pgtype.UUID    `json:"food_id"`
	FoodName    string         `json:"food_name"`
	Price       pgtype.Numeric `json:"price"`
	StockCount  pgtype.Int4    `json:"stock_count"`
	IsAvailable pgtype.Bool    `json:"is_available"`
}

// Locks the food row to check stock during a transaction
func (q *Queries) GetFoodForUpdate(ctx context.Context, foodID pgtype.UUID) (GetFoodForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getFoodForUpdate, foodID)
	var i GetFoodForUpdateRow
	err := row.Scan(
		&i.FoodID,
		&i.FoodName,
		&i.Price,
		&i.StockCount,
		&i.IsAvailable,
	)
	return i, err
}

const getOTPCodeByEntityID = `-- name: GetOTPCodeByEntityID :one
SELECT otp_id, entity_id, entity_role, otp_secret, otp_purpose, otp_attempts, expires_at, created_at, deletion_scheduled_at FROM otp_codes
WHERE entity_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// Don't check expires_at here, we'll handle expiry in code
func (q *Queries) GetOTPCodeByEntityID(ctx context.Context, entityID pgtype.UUID) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getOTPCodeByEntityID, entityID)
	var i OtpCode
	err := row.Scan(
		&i.OtpID,
		&i.EntityID,
		&i.EntityRole,
		&i.OtpSecret,
		&i.OtpPurpose,
		&i.OtpAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const getOTPCodeWithCooldown = `-- name: GetOTPCodeWithCooldown :one
SELECT otp_id, entity_id, entity_role, otp_secret, otp_purpose, otp_attempts, expires_at, created_at, deletion_scheduled_at FROM otp_codes
WHERE entity_id = $1
AND created_at > NOW() - INTERVAL '1 minute'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetOTPCodeWithCooldown(ctx context.Context, entityID pgtype.UUID) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getOTPCodeWithCooldown, entityID)
	var i OtpCode
	err := row.Scan(
		&i.OtpID,
		&i.EntityID,
		&i.EntityRole,
		&i.OtpSecret,
		&i.OtpPurpose,
		&i.OtpAttempts,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.DeletionScheduledAt,
	)
	return i, err
}

const getOrderDetails = `-- name: GetOrderDetails :one
SELECT order_id, user_id, seller_id, total_price, status, delivery_address_json, payment_status, payment_method, created_at FROM user_orders
WHERE order_id = $1 AND user_id = $2
`

type GetOrderDetailsParams struct {
	OrderID pgtype.UUID `json:"order_id"`
	UserID  string      `json:"user_id"`
}

// Secure: checks that the order_id also belongs to the user_id
func (q *Queries) GetOrderDetails(ctx context.Context, arg GetOrderDetailsParams) (UserOrder, error) {
	row := q.db.QueryRow(ctx, getOrderDetails, arg.OrderID, arg.UserID)
	var i UserOrder
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.SellerID,
		&i.TotalPrice,
		&i.Status,
		&i.DeliveryAddressJson,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT order_item_id, order_id, food_id, quantity, price_at_purchase, food_name_snapshot FROM user_order_items
WHERE order_id = $1
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]UserOrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserOrderItem
	for rows.Next() {
		var i UserOrderItem
		if err := rows.Scan(
			&i.OrderItemID,
			&i.OrderID,
			&i.FoodID,
			&i.Quantity,
			&i.PriceAtPurchase,
			&i.FoodNameSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingRegistrationByEmail = `-- name: GetPendingRegistrationByEmail :one

SELECT pending_id, entity_role, email, username, hashed_password, first_name, last_name, raw_data, expires_at, created_at FROM pending_registrations
WHERE email = $1 AND expires_at > NOW()
`

// Return the new pending_id
func (q *Queries) GetPendingRegistrationByEmail(ctx context.Context, email string) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationByEmail, email)
	var i PendingRegistration
	err := row.Scan(
		&i.PendingID,
		&i.EntityRole,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.RawData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingRegistrationByID = `-- name: GetPendingRegistrationByID :one
SELECT pending_id, entity_role, email, username, hashed_password, first_name, last_name, raw_data, expires_at, created_at FROM pending_registrations
WHERE pending_id = $1 AND expires_at > NOW()
`

func (q *Queries) GetPendingRegistrationByID(ctx context.Context, pendingID pgtype.UUID) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationByID, pendingID)
	var i PendingRegistration
	err := row.Scan(
		&i.PendingID,
		&i.EntityRole,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.RawData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingRegistrationByUsername = `-- name: GetPendingRegistrationByUsername :one
SELECT pending_id, entity_role, email, username, hashed_password, first_name, last_name, raw_data, expires_at, created_at FROM pending_registrations
WHERE username = $1 AND expires_at > NOW()
`

func (q *Queries) GetPendingRegistrationByUsername(ctx context.Context, username pgtype.Text) (PendingRegistration, error) {
	row := q.db.QueryRow(ctx, getPendingRegistrationByUsername, username)
	var i PendingRegistration
	err := row.Scan(
		&i.PendingID,
		&i.EntityRole,
		&i.Email,
		&i.Username,
		&i.HashedPassword,
		&i.FirstName,
		&i.LastName,
		&i.RawData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentAuthActivity = `-- name: GetRecentAuthActivity :many
SELECT log_id, user_id, log_category, log_action, log_message, log_level, ip_address, user_agent, metadata, created_at FROM logs_auth
WHERE user_id = $1
  AND created_at > $2
ORDER BY created_at DESC
LIMIT $3
`

type GetRecentAuthActivityParams struct {
	UserID    pgtype.Text        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) GetRecentAuthActivity(ctx context.Context, arg GetRecentAuthActivityParams) ([]LogsAuth, error) {
	rows, err := q.db.Query(ctx, getRecentAuthActivity, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogsAuth
	for rows.Next() {
		var i LogsAuth
		if err := rows.Scan(
			&i.LogID,
			&i.UserID,
			&i.LogCategory,
			&i.LogAction,
			&i.LogMessage,
			&i.LogLevel,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, device_info, ip_address, expires_at, created_at, revoked_at, replaced_by_token_id FROM users_refresh_tokens
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (UsersRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i UsersRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.ReplacedByTokenID,
	)
	return i, err
}

const getUserActiveRefreshTokens = `-- name: GetUserActiveRefreshTokens :many
SELECT id, user_id, token_hash, device_info, ip_address, expires_at, created_at, revoked_at, replaced_by_token_id FROM users_refresh_tokens
WHERE user_id = $1 
  AND revoked_at IS NULL 
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

// Unused queries
func (q *Queries) GetUserActiveRefreshTokens(ctx context.Context, userID string) ([]UsersRefreshToken, error) {
	rows, err := q.db.Query(ctx, getUserActiveRefreshTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersRefreshToken
	for rows.Next() {
		var i UsersRefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.ReplacedByTokenID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAddressByID = `-- name: GetUserAddressByID :one
SELECT address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, recipient_name, recipient_phone, delivery_notes, is_default, is_active, created_at, updated_at FROM user_addresses
WHERE address_id = $1 AND user_id = $2 AND is_active = true
`

type GetUserAddressByIDParams struct {
	AddressID pgtype.UUID `json:"address_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) GetUserAddressByID(ctx context.Context, arg GetUserAddressByIDParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, getUserAddressByID, arg.AddressID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.DeliveryNotes,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAddresses = `-- name: GetUserAddresses :many
SELECT address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, recipient_name, recipient_phone, delivery_notes, is_default, is_active, created_at, updated_at FROM user_addresses
WHERE user_id = $1 AND is_active = true
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) GetUserAddresses(ctx context.Context, userID string) ([]UserAddress, error) {
	rows, err := q.db.Query(ctx, getUserAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAddress
	for rows.Next() {
		var i UserAddress
		if err := rows.Scan(
			&i.AddressID,
			&i.UserID,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.AddressCity,
			&i.AddressProvince,
			&i.AddressPostalcode,
			&i.AddressLatitude,
			&i.AddressLongitude,
			&i.AddressLabel,
			&i.RecipientName,
			&i.RecipientPhone,
			&i.DeliveryNotes,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth, is_email_verified, email_verified_at FROM users
WHERE user_email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, userEmail pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, userEmail)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
		&i.IsEmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth, is_email_verified, email_verified_at FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
		&i.IsEmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByOAuthEmail = `-- name: GetUserByOAuthEmail :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth, is_email_verified, email_verified_at FROM users
WHERE user_email_auth = $1 AND user_provider IS NOT NULL
`

func (q *Queries) GetUserByOAuthEmail(ctx context.Context, userEmailAuth pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOAuthEmail, userEmailAuth)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
		&i.IsEmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth, is_email_verified, email_verified_at FROM users
WHERE user_username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, userUsername pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, userUsername)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
		&i.IsEmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const getUserOrders = `-- name: GetUserOrders :many
SELECT order_id, user_id, seller_id, total_price, status, delivery_address_json, payment_status, payment_method, created_at FROM user_orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetUserOrders(ctx context.Context, userID string) ([]UserOrder, error) {
	rows, err := q.db.Query(ctx, getUserOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserOrder
	for rows.Next() {
		var i UserOrder
		if err := rows.Scan(
			&i.OrderID,
			&i.UserID,
			&i.SellerID,
			&i.TotalPrice,
			&i.Status,
			&i.DeliveryAddressJson,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProviderID = `-- name: GetUserProviderID :one
SELECT user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth, is_email_verified, email_verified_at FROM users
WHERE user_provider_user_id = $1 LIMIT 1
`

func (q *Queries) GetUserProviderID(ctx context.Context, userProviderUserID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserProviderID, userProviderUserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
		&i.IsEmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const hardDeleteUserAddress = `-- name: HardDeleteUserAddress :exec
DELETE FROM user_addresses
WHERE address_id = $1 AND user_id = $2
`

type HardDeleteUserAddressParams struct {
	AddressID pgtype.UUID `json:"address_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) HardDeleteUserAddress(ctx context.Context, arg HardDeleteUserAddressParams) error {
	_, err := q.db.Exec(ctx, hardDeleteUserAddress, arg.AddressID, arg.UserID)
	return err
}

const ifAddressIsDefault = `-- name: IfAddressIsDefault :one
SELECT is_default FROM user_addresses
WHERE address_id = $1
`

func (q *Queries) IfAddressIsDefault(ctx context.Context, addressID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ifAddressIsDefault, addressID)
	var is_default bool
	err := row.Scan(&is_default)
	return is_default, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE users_refresh_tokens 
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE users_refresh_tokens 
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const setCartSeller = `-- name: SetCartSeller :exec
UPDATE user_carts
SET seller_id = $2, updated_at = NOW()
WHERE user_id = $1
`

type SetCartSellerParams struct {
	UserID   string      `json:"user_id"`
	SellerID pgtype.UUID `json:"seller_id"`
}

func (q *Queries) SetCartSeller(ctx context.Context, arg SetCartSellerParams) error {
	_, err := q.db.Exec(ctx, setCartSeller, arg.UserID, arg.SellerID)
	return err
}

const setDefaultAddress = `-- name: SetDefaultAddress :one
UPDATE user_addresses
SET is_default = true
WHERE address_id = $1 AND user_id = $2 AND is_active = true
RETURNING address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, recipient_name, recipient_phone, delivery_notes, is_default, is_active, created_at, updated_at
`

type SetDefaultAddressParams struct {
	AddressID pgtype.UUID `json:"address_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, setDefaultAddress, arg.AddressID, arg.UserID)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.DeliveryNotes,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlinkGoogleAccount = `-- name: UnlinkGoogleAccount :exec
UPDATE users
SET 
  user_name_auth = NULL,
  user_provider = NULL,
  user_provider_user_id = NULL,
  user_avatar_url = NULL,   -- Clear the avatar linked to Google
  user_raw_data = NULL,     -- Clear the raw data from Google
  user_updated_at_auth = NOW()
WHERE 
  user_id = $1
`

func (q *Queries) UnlinkGoogleAccount(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, unlinkGoogleAccount, userID)
	return err
}

const unsetDefaultAddress = `-- name: UnsetDefaultAddress :exec
UPDATE user_addresses
SET is_default = false
WHERE user_id = $1 AND address_id != $2 AND is_default = true
`

type UnsetDefaultAddressParams struct {
	UserID    string      `json:"user_id"`
	AddressID pgtype.UUID `json:"address_id"`
}

func (q *Queries) UnsetDefaultAddress(ctx context.Context, arg UnsetDefaultAddressParams) error {
	_, err := q.db.Exec(ctx, unsetDefaultAddress, arg.UserID, arg.AddressID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE user_cart_items
SET quantity = $3
WHERE cart_id = $1 AND food_id = $2
RETURNING cart_item_id, cart_id, food_id, quantity
`

type UpdateCartItemQuantityParams struct {
	CartID   pgtype.UUID `json:"cart_id"`
	FoodID   pgtype.UUID `json:"food_id"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (UserCartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.CartID, arg.FoodID, arg.Quantity)
	var i UserCartItem
	err := row.Scan(
		&i.CartItemID,
		&i.CartID,
		&i.FoodID,
		&i.Quantity,
	)
	return i, err
}

const updateOTPAttempts = `-- name: UpdateOTPAttempts :exec
UPDATE otp_codes
SET otp_attempts = otp_attempts + 1
WHERE otp_id = $1
`

func (q *Queries) UpdateOTPAttempts(ctx context.Context, otpID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateOTPAttempts, otpID)
	return err
}

const updateRefreshTokenReplacement = `-- name: UpdateRefreshTokenReplacement :exec
UPDATE users_refresh_tokens
SET replaced_by_token_id = $2
WHERE id = $1
`

type UpdateRefreshTokenReplacementParams struct {
	ID                pgtype.UUID `json:"id"`
	ReplacedByTokenID pgtype.UUID `json:"replaced_by_token_id"`
}

func (q *Queries) UpdateRefreshTokenReplacement(ctx context.Context, arg UpdateRefreshTokenReplacementParams) error {
	_, err := q.db.Exec(ctx, updateRefreshTokenReplacement, arg.ID, arg.ReplacedByTokenID)
	return err
}

const updateUserAddress = `-- name: UpdateUserAddress :one
UPDATE user_addresses
SET 
    address_line1 = COALESCE($3, address_line1),
    address_line2 = COALESCE($4, address_line2),
    address_city = COALESCE($5, address_city),
    address_province = COALESCE($6, address_province),
    address_postalcode = COALESCE($7, address_postalcode),
    address_latitude = COALESCE($8, address_latitude),
    address_longitude = COALESCE($9, address_longitude),
    address_label = COALESCE($10, address_label),
    recipient_name = COALESCE($11, recipient_name),
    recipient_phone = COALESCE($12, recipient_phone),
    delivery_notes = COALESCE($13, delivery_notes)
WHERE address_id = $1 AND user_id = $2 AND is_active = true
RETURNING address_id, user_id, address_line1, address_line2, address_city, address_province, address_postalcode, address_latitude, address_longitude, address_label, recipient_name, recipient_phone, delivery_notes, is_default, is_active, created_at, updated_at
`

type UpdateUserAddressParams struct {
	AddressID         pgtype.UUID   `json:"address_id"`
	UserID            string        `json:"user_id"`
	AddressLine1      pgtype.Text   `json:"address_line1"`
	AddressLine2      pgtype.Text   `json:"address_line2"`
	AddressCity       pgtype.Text   `json:"address_city"`
	AddressProvince   pgtype.Text   `json:"address_province"`
	AddressPostalcode pgtype.Text   `json:"address_postalcode"`
	AddressLatitude   pgtype.Float8 `json:"address_latitude"`
	AddressLongitude  pgtype.Float8 `json:"address_longitude"`
	AddressLabel      pgtype.Text   `json:"address_label"`
	RecipientName     pgtype.Text   `json:"recipient_name"`
	RecipientPhone    pgtype.Text   `json:"recipient_phone"`
	DeliveryNotes     pgtype.Text   `json:"delivery_notes"`
}

func (q *Queries) UpdateUserAddress(ctx context.Context, arg UpdateUserAddressParams) (UserAddress, error) {
	row := q.db.QueryRow(ctx, updateUserAddress,
		arg.AddressID,
		arg.UserID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.AddressCity,
		arg.AddressProvince,
		arg.AddressPostalcode,
		arg.AddressLatitude,
		arg.AddressLongitude,
		arg.AddressLabel,
		arg.RecipientName,
		arg.RecipientPhone,
		arg.DeliveryNotes,
	)
	var i UserAddress
	err := row.Scan(
		&i.AddressID,
		&i.UserID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.AddressCity,
		&i.AddressProvince,
		&i.AddressPostalcode,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.AddressLabel,
		&i.RecipientName,
		&i.RecipientPhone,
		&i.DeliveryNotes,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
SET user_email = $2,
    user_updated_at_auth = NOW()
WHERE user_id = $1
`

type UpdateUserEmailParams struct {
	UserID    string      `json:"user_id"`
	UserEmail pgtype.Text `json:"user_email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.UserID, arg.UserEmail)
	return err
}

const updateUserGoogleLink = `-- name: UpdateUserGoogleLink :exec
UPDATE users
SET 
  user_name_auth = $1,
  user_avatar_url = $2,
  user_provider = $3,
  user_provider_user_id = $4,
  user_raw_data = $5,
  user_email_auth = $6,
  user_updated_at_auth = NOW()
WHERE 
  user_id = $7
`

type UpdateUserGoogleLinkParams struct {
	UserNameAuth       pgtype.Text `json:"user_name_auth"`
	UserAvatarUrl      pgtype.Text `json:"user_avatar_url"`
	UserProvider       pgtype.Text `json:"user_provider"`
	UserProviderUserID pgtype.Text `json:"user_provider_user_id"`
	UserRawData        []byte      `json:"user_raw_data"`
	UserEmailAuth      pgtype.Text `json:"user_email_auth"`
	UserID             string      `json:"user_id"`
}

func (q *Queries) UpdateUserGoogleLink(ctx context.Context, arg UpdateUserGoogleLinkParams) error {
	_, err := q.db.Exec(ctx, updateUserGoogleLink,
		arg.UserNameAuth,
		arg.UserAvatarUrl,
		arg.UserProvider,
		arg.UserProviderUserID,
		arg.UserRawData,
		arg.UserEmailAuth,
		arg.UserID,
	)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET user_last_login_at = CURRENT_TIMESTAMP
WHERE user_id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, userID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET user_password = $2,
    user_updated_at_auth = NOW()
WHERE user_id = $1
`

type UpdateUserPasswordParams struct {
	UserID       string      `json:"user_id"`
	UserPassword pgtype.Text `json:"user_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.UserID, arg.UserPassword)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET 
    user_firstname = COALESCE($2, user_firstname),
    user_lastname = COALESCE($3, user_lastname),
    user_email = COALESCE($4, user_email),
    user_dob = COALESCE($5, user_dob),
    user_gender = COALESCE($6, user_gender)
WHERE user_id = $1
RETURNING user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth, is_email_verified, email_verified_at
`

type UpdateUserProfileParams struct {
	UserID        string              `json:"user_id"`
	UserFirstname pgtype.Text         `json:"user_firstname"`
	UserLastname  pgtype.Text         `json:"user_lastname"`
	UserEmail     pgtype.Text         `json:"user_email"`
	UserDob       pgtype.Date         `json:"user_dob"`
	UserGender    NullUsersUserGender `json:"user_gender"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.UserFirstname,
		arg.UserLastname,
		arg.UserEmail,
		arg.UserDob,
		arg.UserGender,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
		&i.IsEmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const updateUserUsername = `-- name: UpdateUserUsername :exec
UPDATE users
SET user_username = $2,
    user_updated_at_auth = NOW()
WHERE user_id = $1
`

type UpdateUserUsernameParams struct {
	UserID       string      `json:"user_id"`
	UserUsername pgtype.Text `json:"user_username"`
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUserUsername, arg.UserID, arg.UserUsername)
	return err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO user_cart_items (
    cart_id,
    food_id,
    quantity
) VALUES (
    $1, $2, $3
)
ON CONFLICT (cart_id, food_id)
DO UPDATE SET
    quantity = user_cart_items.quantity + $3
RETURNING cart_item_id, cart_id, food_id, quantity
`

type UpsertCartItemParams struct {
	CartID   pgtype.UUID `json:"cart_id"`
	FoodID   pgtype.UUID `json:"food_id"`
	Quantity int32       `json:"quantity"`
}

// Adds an item to the cart, or increases its quantity if it already exists
func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (UserCartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem, arg.CartID, arg.FoodID, arg.Quantity)
	var i UserCartItem
	err := row.Scan(
		&i.CartItemID,
		&i.CartID,
		&i.FoodID,
		&i.Quantity,
	)
	return i, err
}

const upsertOAuthUser = `-- name: UpsertOAuthUser :one
INSERT INTO users (
    user_id,
    user_email,
    user_name_auth,
    user_avatar_url,
    user_provider,
    user_provider_user_id,
    user_raw_data,
    user_last_login_at,
    user_email_auth,
    user_username,
    user_password
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (user_provider, user_provider_user_id) 
DO UPDATE SET 
    -- Update fields based on EXCLUDED (the row that was attempted to be inserted)
    user_email = COALESCE(EXCLUDED.user_email, users.user_email),
    user_name_auth = EXCLUDED.user_name_auth,
    user_avatar_url = EXCLUDED.user_avatar_url,
    user_raw_data = EXCLUDED.user_raw_data,
    user_last_login_at = EXCLUDED.user_last_login_at, -- Menggunakan nilai login time dari EXCLUDED ($8)
    user_updated_at_auth = CURRENT_TIMESTAMP -- Menggunakan CURRENT_TIMESTAMP untuk mencatat pembaruan skema auth
RETURNING user_id, user_username, user_password, user_firstname, user_lastname, user_email, user_dob, user_gender, user_accounttype, user_name_auth, user_avatar_url, user_provider, user_provider_user_id, user_raw_data, user_created_at_auth, user_updated_at_auth, user_last_login_at, user_email_auth, is_email_verified, email_verified_at
`

type UpsertOAuthUserParams struct {
	UserID             string             `json:"user_id"`
	UserEmail          pgtype.Text        `json:"user_email"`
	UserNameAuth       pgtype.Text        `json:"user_name_auth"`
	UserAvatarUrl      pgtype.Text        `json:"user_avatar_url"`
	UserProvider       pgtype.Text        `json:"user_provider"`
	UserProviderUserID pgtype.Text        `json:"user_provider_user_id"`
	UserRawData        []byte             `json:"user_raw_data"`
	UserLastLoginAt    pgtype.Timestamptz `json:"user_last_login_at"`
	UserEmailAuth      pgtype.Text        `json:"user_email_auth"`
	UserUsername       pgtype.Text        `json:"user_username"`
	UserPassword       pgtype.Text        `json:"user_password"`
}

// OAuth Integration - Upsert user with OAuth data
func (q *Queries) UpsertOAuthUser(ctx context.Context, arg UpsertOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertOAuthUser,
		arg.UserID,
		arg.UserEmail,
		arg.UserNameAuth,
		arg.UserAvatarUrl,
		arg.UserProvider,
		arg.UserProviderUserID,
		arg.UserRawData,
		arg.UserLastLoginAt,
		arg.UserEmailAuth,
		arg.UserUsername,
		arg.UserPassword,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.UserUsername,
		&i.UserPassword,
		&i.UserFirstname,
		&i.UserLastname,
		&i.UserEmail,
		&i.UserDob,
		&i.UserGender,
		&i.UserAccounttype,
		&i.UserNameAuth,
		&i.UserAvatarUrl,
		&i.UserProvider,
		&i.UserProviderUserID,
		&i.UserRawData,
		&i.UserCreatedAtAuth,
		&i.UserUpdatedAtAuth,
		&i.UserLastLoginAt,
		&i.UserEmailAuth,
		&i.IsEmailVerified,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const verifyOTPAtomic = `-- name: VerifyOTPAtomic :one
SELECT verify_otp_atomic FROM verify_otp_atomic($1, $2)
`

type VerifyOTPAtomicParams struct {
	PEntityID    pgtype.UUID `json:"p_entity_id"`
	PMaxAttempts int32       `json:"p_max_attempts"`
}

func (q *Queries) VerifyOTPAtomic(ctx context.Context, arg VerifyOTPAtomicParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, verifyOTPAtomic, arg.PEntityID, arg.PMaxAttempts)
	var verify_otp_atomic interface{}
	err := row.Scan(&verify_otp_atomic)
	return verify_otp_atomic, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET is_email_verified = $2,
    email_verified_at = $3
WHERE user_id = $1
`

type VerifyUserEmailParams struct {
	UserID          string             `json:"user_id"`
	IsEmailVerified pgtype.Bool        `json:"is_email_verified"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

func (q *Queries) VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, arg.UserID, arg.IsEmailVerified, arg.EmailVerifiedAt)
	return err
}
